name : CI - Tests Python

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Cloner le code source
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4

      - name: Lancer les tests
        run: python -m unittest discover -s tests

    
    

