name : CI - Tests Python

on:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Cloner le code
        run: eactions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4

      - name: Lancer les tests
        run: python -m unittest discover -s tests

    
    

